# Generated by Django 5.0.4 on 2024-04-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anz_Fächer', models.IntegerField()),
                ('bes_Plätze', models.IntegerField()),
                ('Standort', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Waren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hersteller', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Kaufdatum', models.DateTimeField()),
                ('Geschichte', models.TextField()),
                ('Eigentümer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.kategorie')),
                ('Regal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.regale')),
            ],
        ),
    ]
