# Generated by Django 5.0.4 on 2024-04-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waren',
            name='Kategorie',
        ),
        migrations.RemoveField(
            model_name='waren',
            name='Regal',
        ),
        migrations.RemoveField(
            model_name='waren',
            name='Eigentümer',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.DeleteModel(
            name='Regale',
        ),
        migrations.DeleteModel(
            name='Waren',
        ),
    ]
