# Generated by Django 5.0.4 on 2024-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regale',
            old_name='bes_Plätze',
            new_name='bes_Fächer',
        ),
        migrations.AlterField(
            model_name='waren',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
