# Generated by Django 5.0.4 on 2024-04-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0004_rename_bes_plätze_regale_bes_fächer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waren',
            name='Kategorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.kategorie'),
        ),
        migrations.AlterField(
            model_name='waren',
            name='Regal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.regale'),
        ),
    ]
