# Generated by Django 5.0.4 on 2024-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0005_alter_waren_kategorie_alter_waren_regal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waren',
            name='Kaufdatum',
            field=models.DateField(),
        ),
    ]
