# Generated by Django 5.0.4 on 2024-04-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0006_alter_waren_kaufdatum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waren',
            name='Kaufdatum',
        ),
    ]
