# Generated by Django 5.0.4 on 2024-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0007_remove_waren_kaufdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='regale',
            name='name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
