# Generated by Django 5.0.4 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0009_waren_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waren',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
