# Generated by Django 5.0.4 on 2024-04-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0010_alter_waren_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waren',
            name='Kategorie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.kategorie'),
        ),
        migrations.AlterField(
            model_name='waren',
            name='Regal',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.regale'),
        ),
    ]
