# Generated by Django 5.0.4 on 2024-04-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0011_alter_waren_kategorie_alter_waren_regal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waren',
            name='Kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.kategorie'),
        ),
        migrations.AlterField(
            model_name='waren',
            name='Regal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionmanager.regale'),
        ),
    ]
