# Generated by Django 5.0.4 on 2024-05-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0012_alter_waren_kategorie_alter_waren_regal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='Beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='regale',
            old_name='Standort',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='Kategorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='bild',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='Eigentümer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='Hersteller',
            new_name='producer',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='Regal',
            new_name='shelf',
        ),
        migrations.RenameField(
            model_name='waren',
            old_name='Geschichte',
            new_name='story',
        ),
    ]
