# Generated by Django 5.0.4 on 2024-05-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmanager', '0013_rename_beschreibung_kategorie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waren',
            old_name='producer',
            new_name='brand',
        ),
    ]
